/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'active' : null } |
  { 'veryActive' : null } |
  { 'light' : null } |
  { 'sedentary' : null } |
  { 'moderate' : null };
export interface ContactLead {
  'id' : bigint,
  'area' : string,
  'name' : string,
  'planInterest' : string,
  'phone' : string,
}
export type DietType = { 'veg' : null } |
  { 'nonVeg' : null };
export interface EnrichedDietCalculation {
  'id' : bigint,
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'calories' : number,
  'goal' : Goal,
  'weightKg' : number,
  'gender' : Gender,
  'dietType' : DietType,
  'protein' : number,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export type Goal = { 'fatLoss' : null } |
  { 'muscleGain' : null };
export interface Recipe {
  'id' : bigint,
  'fat' : number,
  'imagePath' : string,
  'carbs' : number,
  'calories' : number,
  'name' : string,
  'description' : string,
  'category' : string,
  'protein' : number,
}
export interface Testimonial {
  'id' : bigint,
  'resultDescription' : string,
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addContactLead' : ActorMethod<[string, string, string, string], undefined>,
  'addRecipe' : ActorMethod<
    [string, string, number, number, number, number, string, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, bigint, string, string], undefined>,
  'calculateDiet' : ActorMethod<
    [Gender, bigint, number, number, ActivityLevel, DietType, Goal],
    EnrichedDietCalculation
  >,
  'getAllContactLeads' : ActorMethod<[], Array<ContactLead>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];