/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const ActivityLevel = IDL.Variant({
  'active' : IDL.Null,
  'veryActive' : IDL.Null,
  'light' : IDL.Null,
  'sedentary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const DietType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
export const Goal = IDL.Variant({
  'fatLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
});
export const EnrichedDietCalculation = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'calories' : IDL.Float64,
  'goal' : Goal,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
  'dietType' : DietType,
  'protein' : IDL.Float64,
});
export const ContactLead = IDL.Record({
  'id' : IDL.Nat,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'planInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Float64,
  'imagePath' : IDL.Text,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'protein' : IDL.Float64,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'resultDescription' : IDL.Text,
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addContactLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'calculateDiet' : IDL.Func(
      [
        Gender,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        ActivityLevel,
        DietType,
        Goal,
      ],
      [EnrichedDietCalculation],
      [],
    ),
  'getAllContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const ActivityLevel = IDL.Variant({
    'active' : IDL.Null,
    'veryActive' : IDL.Null,
    'light' : IDL.Null,
    'sedentary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const DietType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
  const Goal = IDL.Variant({ 'fatLoss' : IDL.Null, 'muscleGain' : IDL.Null });
  const EnrichedDietCalculation = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'calories' : IDL.Float64,
    'goal' : Goal,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
    'dietType' : DietType,
    'protein' : IDL.Float64,
  });
  const ContactLead = IDL.Record({
    'id' : IDL.Nat,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'planInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Float64,
    'imagePath' : IDL.Text,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'resultDescription' : IDL.Text,
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addContactLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'calculateDiet' : IDL.Func(
        [
          Gender,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          ActivityLevel,
          DietType,
          Goal,
        ],
        [EnrichedDietCalculation],
        [],
      ),
    'getAllContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };