/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactLead {
    id: bigint;
    area: string;
    name: string;
    planInterest: string;
    phone: string;
}
export interface Recipe {
    id: bigint;
    fat: number;
    imagePath: string;
    carbs: number;
    calories: number;
    name: string;
    description: string;
    category: string;
    protein: number;
}
export interface EnrichedDietCalculation {
    id: bigint;
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    calories: number;
    goal: Goal;
    weightKg: number;
    gender: Gender;
    dietType: DietType;
    protein: number;
}
export interface Testimonial {
    id: bigint;
    resultDescription: string;
    name: string;
    reviewText: string;
    rating: bigint;
}
export enum ActivityLevel {
    active = "active",
    veryActive = "veryActive",
    light = "light",
    sedentary = "sedentary",
    moderate = "moderate"
}
export enum DietType {
    veg = "veg",
    nonVeg = "nonVeg"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Goal {
    fatLoss = "fatLoss",
    muscleGain = "muscleGain"
}
export interface backendInterface {
    addContactLead(name: string, phone: string, area: string, planInterest: string): Promise<void>;
    addRecipe(name: string, category: string, protein: number, carbs: number, fat: number, calories: number, description: string, imagePath: string): Promise<void>;
    addTestimonial(name: string, rating: bigint, reviewText: string, resultDescription: string): Promise<void>;
    calculateDiet(gender: Gender, age: bigint, weightKg: number, heightCm: number, activityLevel: ActivityLevel, dietType: DietType, goal: Goal): Promise<EnrichedDietCalculation>;
    getAllContactLeads(): Promise<Array<ContactLead>>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
}
import type { ActivityLevel as _ActivityLevel, DietType as _DietType, EnrichedDietCalculation as _EnrichedDietCalculation, Gender as _Gender, Goal as _Goal } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContactLead(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactLead(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactLead(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addRecipe(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addTestimonial(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async calculateDiet(arg0: Gender, arg1: bigint, arg2: number, arg3: number, arg4: ActivityLevel, arg5: DietType, arg6: Goal): Promise<EnrichedDietCalculation> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateDiet(to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_ActivityLevel_n3(this._uploadFile, this._downloadFile, arg4), to_candid_DietType_n5(this._uploadFile, this._downloadFile, arg5), to_candid_Goal_n7(this._uploadFile, this._downloadFile, arg6));
                return from_candid_EnrichedDietCalculation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateDiet(to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_ActivityLevel_n3(this._uploadFile, this._downloadFile, arg4), to_candid_DietType_n5(this._uploadFile, this._downloadFile, arg5), to_candid_Goal_n7(this._uploadFile, this._downloadFile, arg6));
            return from_candid_EnrichedDietCalculation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactLeads(): Promise<Array<ContactLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactLeads();
            return result;
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
}
function from_candid_ActivityLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DietType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietType): DietType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_EnrichedDietCalculation_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrichedDietCalculation): EnrichedDietCalculation {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    activityLevel: _ActivityLevel;
    heightCm: number;
    calories: number;
    goal: _Goal;
    weightKg: number;
    gender: _Gender;
    dietType: _DietType;
    protein: number;
}): {
    id: bigint;
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    calories: number;
    goal: Goal;
    weightKg: number;
    gender: Gender;
    dietType: DietType;
    protein: number;
} {
    return {
        id: value.id,
        age: value.age,
        activityLevel: from_candid_ActivityLevel_n11(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        calories: value.calories,
        goal: from_candid_Goal_n13(_uploadFile, _downloadFile, value.goal),
        weightKg: value.weightKg,
        gender: from_candid_Gender_n15(_uploadFile, _downloadFile, value.gender),
        dietType: from_candid_DietType_n17(_uploadFile, _downloadFile, value.dietType),
        protein: value.protein
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
}): ActivityLevel {
    return "active" in value ? ActivityLevel.active : "veryActive" in value ? ActivityLevel.veryActive : "light" in value ? ActivityLevel.light : "sedentary" in value ? ActivityLevel.sedentary : "moderate" in value ? ActivityLevel.moderate : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fatLoss: null;
} | {
    muscleGain: null;
}): Goal {
    return "fatLoss" in value ? Goal.fatLoss : "muscleGain" in value ? Goal.muscleGain : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    nonVeg: null;
}): DietType {
    return "veg" in value ? DietType.veg : "nonVeg" in value ? DietType.nonVeg : value;
}
function to_candid_ActivityLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DietType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): _DietType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
} {
    return value == ActivityLevel.active ? {
        active: null
    } : value == ActivityLevel.veryActive ? {
        veryActive: null
    } : value == ActivityLevel.light ? {
        light: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): {
    veg: null;
} | {
    nonVeg: null;
} {
    return value == DietType.veg ? {
        veg: null
    } : value == DietType.nonVeg ? {
        nonVeg: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    fatLoss: null;
} | {
    muscleGain: null;
} {
    return value == Goal.fatLoss ? {
        fatLoss: null
    } : value == Goal.muscleGain ? {
        muscleGain: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
